hamsterdb Embedded Database: hamsterdb::env Class Reference
hamsterdb::env Class Reference
#include <hamsterdb.hpp>
Public Member Functions
env ()
~env ()
void create (const char *filename, uint32_t flags=0, uint32_t mode=0644, const ham_parameter_t *param=0)
void open (const char *filename, uint32_t flags=0, const ham_parameter_t *param=0)
void flush (uint32_t flags=0)
db create_db (uint16_t name, uint32_t flags=0, const ham_parameter_t *param=0)
db open_db (uint16_t name, uint32_t flags=0, const ham_parameter_t *param=0)
void rename_db (uint16_t oldname, uint16_t newname, uint32_t flags=0)
void erase_db (uint16_t name, uint32_t flags=0)
txn begin (const char *name=0)
void close (uint32_t flags=0)
void get_parameters (ham_parameter_t *param)
std::vector< uint16_t > get_database_names ()
Private Attributes
ham_env_t * m_env
Detailed Description
An Environment class.
This class wraps the ham_env_t structure.
Definition at line 608 of file hamsterdb.hpp.
Constructor & Destructor Documentation
hamsterdb::env::env () inline
Constructor
Definition at line 611 of file hamsterdb.hpp.
hamsterdb::env::~env () inline
Destructor - automatically closes the Environment, if necessary.
!! Any exception is silently discarded. Use of the destructor to close environments is therefore not recommended, because there are valid reasons why an Exception can be thrown (i.e. not all Databases were closed or not all Transactions were committed/aborted).
An assert() was added to catch this condition in debug builds.
Definition at line 626 of file hamsterdb.hpp.
References close(), and hamsterdb::error::get_errno().
Member Function Documentation
txn hamsterdb::env::begin (const char * name = 0) inline
Begin a new Transaction
Definition at line 697 of file hamsterdb.hpp.
References error(), ham_txn_begin(), and m_env.
void hamsterdb::env::close (uint32_t flags = 0) inline
Closes the Environment.
Definition at line 707 of file hamsterdb.hpp.
References error(), HAM_AUTO_CLEANUP, ham_env_close(), and m_env.
Referenced by run_demo(), and ~env().
void hamsterdb::env::create (const char * filename, uint32_t flags = 0, uint32_t mode = 0644, const ham_parameter_t * param = 0) inline
Creates a new Environment.
Definition at line 636 of file hamsterdb.hpp.
References error(), ham_env_create(), and m_env.
Referenced by run_demo().
db hamsterdb::env::create_db (uint16_t name, uint32_t flags = 0, const ham_parameter_t * param = 0) inline
Creates a new Database in the Environment.
Definition at line 659 of file hamsterdb.hpp.
References error(), ham_env_create_db(), and m_env.
Referenced by run_demo().
void hamsterdb::env::erase_db (uint16_t name, uint32_t flags = 0) inline
Deletes a Database from the Environment.
Definition at line 690 of file hamsterdb.hpp.
References error(), ham_env_erase_db(), and m_env.
void hamsterdb::env::flush (uint32_t flags = 0) inline
Flushes the Environment to disk.
Definition at line 652 of file hamsterdb.hpp.
References error(), ham_env_flush(), and m_env.
std::vector<uint16_t> hamsterdb::env::get_database_names () inline
Get all Database names.
Definition at line 727 of file hamsterdb.hpp.
References error(), ham_env_get_database_names(), HAM_LIMITS_REACHED, and m_env.
void hamsterdb::env::get_parameters (ham_parameter_t * param) inline
Retrieves Environment parameters.
Definition at line 720 of file hamsterdb.hpp.
References error(), ham_env_get_parameters(), and m_env.
void hamsterdb::env::open (const char * filename, uint32_t flags = 0, const ham_parameter_t * param = 0) inline
Opens an existing Environment.
Definition at line 644 of file hamsterdb.hpp.
References error(), ham_env_open(), and m_env.
Referenced by run_demo().
db hamsterdb::env::open_db (uint16_t name, uint32_t flags = 0, const ham_parameter_t * param = 0) inline
Opens an existing Database in the Environment.
Definition at line 671 of file hamsterdb.hpp.
References error(), ham_env_open_db(), and m_env.
Referenced by run_demo().
void hamsterdb::env::rename_db (uint16_t oldname, uint16_t newname, uint32_t flags = 0) inline
Renames an existing Database in the Environment.
Definition at line 683 of file hamsterdb.hpp.
References error(), ham_env_rename_db(), and m_env.
Field Documentation
ham_env_t* hamsterdb::env::m_env private
Definition at line 747 of file hamsterdb.hpp.
Referenced by begin(), close(), create(), create_db(), erase_db(), flush(), get_database_names(), get_parameters(), open(), open_db(), and rename_db().
The documentation for this class was generated from the following file:
include/ham/hamsterdb.hpp