hamsterdb Embedded Database: hamsterdb::record Class Reference
hamsterdb::record Class Reference
#include <hamsterdb.hpp>
Public Member Functions
record (void *data=0, uint32_t size=0, uint32_t flags=0)
record (const record &other)
record & operator= (const record &other)
void * get_data () const
void set_data (void *data)
uint32_t get_size () const
void set_size (uint32_t size)
uint32_t get_flags () const
void set_flags (uint32_t flags)
ham_record_t * get_handle ()
Protected Attributes
ham_record_t m_rec
Detailed Description
A record class.
This class wraps structures of type ham_record_t.
Definition at line 170 of file hamsterdb.hpp.
Constructor & Destructor Documentation
hamsterdb::record::record (void * data = 0, uint32_t size = 0, uint32_t flags = 0) inline
Constructor
Definition at line 173 of file hamsterdb.hpp.
References ham_record_t::data, ham_record_t::flags, m_rec, and ham_record_t::size.
hamsterdb::record::record (const record & other) inline
Copy constructor.
Definition at line 181 of file hamsterdb.hpp.
Member Function Documentation
void* hamsterdb::record::get_data () const inline
Returns the record data.
Definition at line 192 of file hamsterdb.hpp.
References ham_record_t::data, and m_rec.
Referenced by run_demo().
uint32_t hamsterdb::record::get_flags () const inline
Returns the flags of the record.
Definition at line 212 of file hamsterdb.hpp.
References ham_record_t::flags, and m_rec.
ham_record_t* hamsterdb::record::get_handle () inline
Returns a pointer to the internal ham_record_t structure.
Definition at line 222 of file hamsterdb.hpp.
References m_rec.
Referenced by hamsterdb::db::find(), hamsterdb::db::insert(), hamsterdb::cursor::insert(), hamsterdb::cursor::move(), and hamsterdb::cursor::overwrite().
uint32_t hamsterdb::record::get_size () const inline
Returns the size of the record.
Definition at line 202 of file hamsterdb.hpp.
References m_rec, and ham_record_t::size.
record& hamsterdb::record::operator= (const record & other) inline
Assignment operator.
Definition at line 186 of file hamsterdb.hpp.
References m_rec.
void hamsterdb::record::set_data (void * data) inline
Sets the record data.
Definition at line 197 of file hamsterdb.hpp.
References ham_record_t::data, and m_rec.
Referenced by run_demo().
void hamsterdb::record::set_flags (uint32_t flags) inline
Sets the flags of the record.
Definition at line 217 of file hamsterdb.hpp.
References ham_record_t::flags, and m_rec.
void hamsterdb::record::set_size (uint32_t size) inline
Sets the size of the record.
Definition at line 207 of file hamsterdb.hpp.
References m_rec, and ham_record_t::size.
Referenced by run_demo().
Field Documentation
ham_record_t hamsterdb::record::m_rec protected
Definition at line 227 of file hamsterdb.hpp.
Referenced by get_data(), get_flags(), get_handle(), get_size(), operator=(), record(), set_data(), set_flags(), and set_size().
The documentation for this class was generated from the following file:
include/ham/hamsterdb.hpp