hamsterdb Embedded Database: hamsterdb::db Class Reference
hamsterdb::db Class Reference
#include <hamsterdb.hpp>
Public Member Functions
db ()
~db ()
db & operator= (const db &other)
ham_status_t get_error ()
void set_compare_func (ham_compare_func_t foo)
record find (txn *t, key *k, uint32_t flags=0)
record & find (txn *t, key *k, record *r, uint32_t flags=0)
record find (key *k, uint32_t flags=0)
void insert (txn *t, key *k, record *r, uint32_t flags=0)
void insert (key *k, record *r, uint32_t flags=0)
void erase (key *k, uint32_t flags=0)
void erase (txn *t, key *k, uint32_t flags=0)
uint64_t get_key_count (ham_txn_t *txn=0, uint32_t flags=0)
void get_parameters (ham_parameter_t *param)
void close (uint32_t flags=0)
ham_db_t * get_handle ()
Static Public Member Functions
static void set_errhandler (ham_errhandler_fun f)
static void get_version (uint32_t *major, uint32_t *minor, uint32_t *revision)
Protected Member Functions
db (ham_db_t *db)
Private Attributes
ham_db_t * m_db
Friends
class env
Detailed Description
A Database class.
This class wraps the ham_db_t Database handles.
Definition at line 277 of file hamsterdb.hpp.
Constructor & Destructor Documentation
hamsterdb::db::db () inline
Constructor
Definition at line 291 of file hamsterdb.hpp.
hamsterdb::db::~db () inline
Destructor - automatically closes the Database, if necessary.
!! Any exception is silently discarded. Use of the destructor to clean up open databases is therefore not recommended, because there are valid reasons why an Exception can be thrown (i.e. not all Cursors of this database were closed).
An assert() was added to catch this condition in debug builds.
Definition at line 306 of file hamsterdb.hpp.
References close(), and hamsterdb::error::get_errno().
hamsterdb::db::db (ham_db_t * db) inline protected
Definition at line 438 of file hamsterdb.hpp.
Member Function Documentation
void hamsterdb::db::close (uint32_t flags = 0) inline
Closes the Database.
Definition at line 417 of file hamsterdb.hpp.
References error(), HAM_AUTO_CLEANUP, ham_db_close(), and m_db.
Referenced by operator=(), run_demo(), and ~db().
void hamsterdb::db::erase (key * k, uint32_t flags = 0) inline
Erases a key/record pair.
Definition at line 387 of file hamsterdb.hpp.
Referenced by run_demo().
void hamsterdb::db::erase (txn * t, key * k, uint32_t flags = 0) inline
Erases a key/record pair.
Definition at line 392 of file hamsterdb.hpp.
References error(), hamsterdb::key::get_handle(), hamsterdb::txn::get_handle(), ham_db_erase(), and m_db.
record hamsterdb::db::find (txn * t, key * k, uint32_t flags = 0) inline
Finds a record by looking up the key.
Definition at line 344 of file hamsterdb.hpp.
References error(), hamsterdb::key::get_handle(), hamsterdb::record::get_handle(), hamsterdb::txn::get_handle(), ham_db_find(), and m_db.
Referenced by find(), and run_demo().
record& hamsterdb::db::find (txn * t, key * k, record * r, uint32_t flags = 0) inline
Finds a record by looking up the key.
Definition at line 356 of file hamsterdb.hpp.
References error(), hamsterdb::key::get_handle(), hamsterdb::record::get_handle(), hamsterdb::txn::get_handle(), ham_db_find(), and m_db.
record hamsterdb::db::find (key * k, uint32_t flags = 0) inline
Finds a record by looking up the key.
Definition at line 367 of file hamsterdb.hpp.
References find().
ham_status_t hamsterdb::db::get_error () inline
Returns the last Database error.
Definition at line 332 of file hamsterdb.hpp.
References ham_db_get_error(), and m_db.
ham_db_t* hamsterdb::db::get_handle () inline
Returns a pointer to the internal ham_db_t structure.
Definition at line 430 of file hamsterdb.hpp.
References m_db.
Referenced by hamsterdb::cursor::create().
uint64_t hamsterdb::db::get_key_count (ham_txn_t * txn = 0, uint32_t flags = 0) inline
Returns number of items in the Database.
Definition at line 401 of file hamsterdb.hpp.
References error(), ham_db_get_key_count(), and m_db.
void hamsterdb::db::get_parameters (ham_parameter_t * param) inline
Retrieves Database parameters.
Definition at line 410 of file hamsterdb.hpp.
References error(), ham_db_get_parameters(), and m_db.
static void hamsterdb::db::get_version (uint32_t * major, uint32_t * minor, uint32_t * revision) inline static
Retrieves the hamsterdb library version.
Definition at line 285 of file hamsterdb.hpp.
References ham_get_version().
void hamsterdb::db::insert (txn * t, key * k, record * r, uint32_t flags = 0) inline
Inserts a key/record pair.
Definition at line 372 of file hamsterdb.hpp.
References error(), hamsterdb::key::get_handle(), hamsterdb::record::get_handle(), hamsterdb::txn::get_handle(), ham_db_insert(), and m_db.
Referenced by insert(), and run_demo().
void hamsterdb::db::insert (key * k, record * r, uint32_t flags = 0) inline
Inserts a key/record pair.
Definition at line 382 of file hamsterdb.hpp.
References insert().
db& hamsterdb::db::operator= (const db & other) inline
Assignment operator.
Important! This operator transfers the ownership of the Database handle.
Definition at line 321 of file hamsterdb.hpp.
References close(), and m_db.
void hamsterdb::db::set_compare_func (ham_compare_func_t foo) inline
Sets the comparison function.
Definition at line 337 of file hamsterdb.hpp.
References error(), ham_db_set_compare_func(), and m_db.
static void hamsterdb::db::set_errhandler (ham_errhandler_fun f) inline static
Set error handler function.
Definition at line 280 of file hamsterdb.hpp.
References ham_set_errhandler().
Friends And Related Function Documentation
friend class env friend
Definition at line 435 of file hamsterdb.hpp.
Field Documentation
ham_db_t* hamsterdb::db::m_db private
Definition at line 443 of file hamsterdb.hpp.
Referenced by close(), erase(), find(), get_error(), get_handle(), get_key_count(), get_parameters(), insert(), operator=(), and set_compare_func().
The documentation for this class was generated from the following file:
include/ham/hamsterdb.hpp