hamsterdb Embedded Database: hamsterdb::key Class Reference
hamsterdb::key Class Reference
#include <hamsterdb.hpp>
Public Member Functions
key (void *data=0, uint16_t size=0, uint32_t flags=0)
key (const key &other)
key & operator= (const key &other)
void * get_data () const
void set_data (void *data)
uint16_t get_size () const
void set_size (uint16_t size)
template<class T >
void set (T &t)
uint32_t get_flags () const
void set_flags (uint32_t flags)
ham_key_t * get_handle ()
int get_approximate_match_type ()
Private Attributes
ham_key_t m_key
Detailed Description
A key class.
This class wraps structures of type ham_key_t.
Definition at line 90 of file hamsterdb.hpp.
Constructor & Destructor Documentation
hamsterdb::key::key (void * data = 0, uint16_t size = 0, uint32_t flags = 0) inline
Constructor
Definition at line 93 of file hamsterdb.hpp.
References ham_key_t::data, error(), ham_key_t::flags, HAM_INV_KEYSIZE, m_key, and ham_key_t::size.
hamsterdb::key::key (const key & other) inline
Copy constructor.
Definition at line 103 of file hamsterdb.hpp.
Member Function Documentation
int hamsterdb::key::get_approximate_match_type () inline
Returns 'sign' of Approximate Match
Definition at line 157 of file hamsterdb.hpp.
References ham_key_get_approximate_match_type(), and m_key.
void* hamsterdb::key::get_data () const inline
Returns the key data.
Definition at line 115 of file hamsterdb.hpp.
References ham_key_t::data, and m_key.
uint32_t hamsterdb::key::get_flags () const inline
Returns the flags of the key.
Definition at line 142 of file hamsterdb.hpp.
References ham_key_t::flags, and m_key.
ham_key_t* hamsterdb::key::get_handle () inline
Returns a pointer to the internal ham_key_t structure.
Definition at line 152 of file hamsterdb.hpp.
References m_key.
Referenced by hamsterdb::db::erase(), hamsterdb::db::find(), hamsterdb::cursor::find(), hamsterdb::db::insert(), hamsterdb::cursor::insert(), and hamsterdb::cursor::move().
uint16_t hamsterdb::key::get_size () const inline
Returns the size of the key.
Definition at line 125 of file hamsterdb.hpp.
References m_key, and ham_key_t::size.
key& hamsterdb::key::operator= (const key & other) inline
Assignment operator.
Definition at line 108 of file hamsterdb.hpp.
References m_key.
template<class T > void hamsterdb::key::set (T & t) inline
Template assignment
Definition at line 136 of file hamsterdb.hpp.
References set_data(), and set_size().
void hamsterdb::key::set_data (void * data) inline
Sets the key data.
Definition at line 120 of file hamsterdb.hpp.
References ham_key_t::data, and m_key.
Referenced by run_demo(), and set().
void hamsterdb::key::set_flags (uint32_t flags) inline
Sets the flags of the key.
Definition at line 147 of file hamsterdb.hpp.
References ham_key_t::flags, and m_key.
void hamsterdb::key::set_size (uint16_t size) inline
Sets the size of the key.
Definition at line 130 of file hamsterdb.hpp.
References m_key, and ham_key_t::size.
Referenced by run_demo(), and set().
Field Documentation
ham_key_t hamsterdb::key::m_key private
Definition at line 162 of file hamsterdb.hpp.
Referenced by get_approximate_match_type(), get_data(), get_flags(), get_handle(), get_size(), key(), operator=(), set_data(), set_flags(), and set_size().
The documentation for this class was generated from the following file:
include/ham/hamsterdb.hpp