hamsterdb Embedded Database: hamsterdb::error Class Reference
hamsterdb::error Class Reference
#include <hamsterdb.hpp>
Public Member Functions
error (ham_status_t st)
ham_status_t get_errno () const
const char * get_string () const
Private Attributes
ham_status_t m_errno
Detailed Description
An error class.
The hamsterdb C++ API throws this class as Exceptions.
Definition at line 64 of file hamsterdb.hpp.
Constructor & Destructor Documentation
hamsterdb::error::error (ham_status_t st) inline
Constructor
Definition at line 67 of file hamsterdb.hpp.
Member Function Documentation
ham_status_t hamsterdb::error::get_errno () const inline
Returns the error code.
Definition at line 72 of file hamsterdb.hpp.
References m_errno.
Referenced by main(), run_demo(), hamsterdb::cursor::~cursor(), hamsterdb::db::~db(), and hamsterdb::env::~env().
const char* hamsterdb::error::get_string () const inline
Returns an English error description.
Definition at line 77 of file hamsterdb.hpp.
References ham_strerror(), and m_errno.
Referenced by main(), and run_demo().
Field Documentation
ham_status_t hamsterdb::error::m_errno private
Definition at line 82 of file hamsterdb.hpp.
Referenced by get_errno(), and get_string().
The documentation for this class was generated from the following file:
include/ham/hamsterdb.hpp