hamsterdb Embedded Database: samples/client1.c File Reference
client1.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ham/hamsterdb.h>
Macros
#define LOOP 1000
Functions
void error (const char *foo, ham_status_t st)
int main (int argc, char **argv)
Macro Definition Documentation
#define LOOP 1000
A simple example which connects to a hamsterdb server (see server1.c), creates a database, inserts some values, looks them up and erases them.
Definition at line 27 of file client1.c.
Referenced by main().
Function Documentation
void error (const char * foo, ham_status_t st)
Definition at line 30 of file client1.c.
References ham_strerror().
Referenced by hamsterdb::txn::abort(), hamsterdb::env::begin(), hamsterdb::cursor::clone(), hamsterdb::db::close(), hamsterdb::cursor::close(), hamsterdb::env::close(), hamsterdb::txn::commit(), hamsterdb::cursor::create(), hamsterdb::env::create(), hamsterdb::env::create_db(), hamsterdb::db::erase(), hamsterdb::cursor::erase(), hamsterdb::env::erase_db(), hamsterdb::db::find(), hamsterdb::cursor::find(), hamsterdb::env::flush(), hamsterdb::env::get_database_names(), hamsterdb::cursor::get_duplicate_count(), hamsterdb::db::get_key_count(), hamsterdb::db::get_parameters(), hamsterdb::env::get_parameters(), hamsterdb::cursor::get_record_size(), hamsterdb::db::insert(), hamsterdb::cursor::insert(), hamsterdb::key::key(), main(), hamsterdb::cursor::move(), hamsterdb::env::open(), hamsterdb::env::open_db(), hamsterdb::cursor::overwrite(), hamsterdb::env::rename_db(), and hamsterdb::db::set_compare_func().
int main (int argc, char ** argv)
Definition at line 36 of file client1.c.
References ham_record_t::data, ham_key_t::data, error(), ham_db_close(), ham_db_erase(), ham_db_find(), ham_db_insert(), ham_env_close(), ham_env_create(), ham_env_open_db(), HAM_KEY_NOT_FOUND, HAM_SUCCESS, LOOP, ham_record_t::size, and ham_key_t::size.