hamsterdb Embedded Database: samples/db3.c File Reference
db3.c File Reference
#include <stdio.h>
#include <string.h>
#include <ham/hamsterdb.h>
Macros
#define DATABASE_NAME 1
Functions
static int my_string_compare (ham_db_t *db, const uint8_t *lhs, uint32_t lhs_length, const uint8_t *rhs, uint32_t rhs_length)
int main (int argc, char **argv)
Macro Definition Documentation
#define DATABASE_NAME 1
This sample uses hamsterdb to sort data from stdin. Every word is inserted into the database (duplicate words are ignored). Then a cursor is used to print all words in sorted order.
Definition at line 26 of file db3.c.
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
Definition at line 41 of file db3.c.
References ham_key_t::data, DATABASE_NAME, HAM_AUTO_CLEANUP, ham_cursor_create(), ham_cursor_move(), HAM_CURSOR_NEXT, ham_db_insert(), ham_db_set_compare_func(), HAM_DUPLICATE_KEY, HAM_ENABLE_DUPLICATE_KEYS, ham_env_close(), ham_env_create(), ham_env_create_db(), HAM_KEY_NOT_FOUND, HAM_PARAM_KEY_TYPE, HAM_PARAM_RECORD_SIZE, HAM_SUCCESS, HAM_TYPE_CUSTOM, my_string_compare(), and ham_key_t::size.
static int my_string_compare (ham_db_t * db, const uint8_t * lhs, uint32_t lhs_length, const uint8_t * rhs, uint32_t rhs_length) static
Definition at line 29 of file db3.c.
Referenced by main().