hamsterdb Embedded Database: samples/db6.cpp File Reference
db6.cpp File Reference
#include <iostream>
#include <ham/hamsterdb.hpp>
Macros
#define LOOP 10
Functions
int run_demo ()
int main (int argc, char **argv)
Macro Definition Documentation
#define LOOP 10
A simple example, which creates a database, inserts some values, looks them up and erases them. Uses the C++ api.
Definition at line 25 of file db6.cpp.
Referenced by run_demo().
Function Documentation
int main (int argc, char ** argv)
Definition at line 127 of file db6.cpp.
References hamsterdb::error::get_errno(), hamsterdb::error::get_string(), and run_demo().
int run_demo ()
Definition at line 28 of file db6.cpp.
References hamsterdb::db::close(), hamsterdb::env::close(), hamsterdb::env::create(), hamsterdb::env::create_db(), hamsterdb::db::erase(), hamsterdb::db::find(), hamsterdb::record::get_data(), hamsterdb::error::get_errno(), hamsterdb::error::get_string(), HAM_KEY_NOT_FOUND, HAM_PARAM_KEY_TYPE, HAM_PARAM_RECORD_SIZE, HAM_TYPE_UINT32, hamsterdb::db::insert(), LOOP, hamsterdb::env::open(), hamsterdb::env::open_db(), hamsterdb::key::set_data(), hamsterdb::record::set_data(), hamsterdb::key::set_size(), and hamsterdb::record::set_size().
Referenced by main().