hamsterdb Embedded Database: samples/env1.c File Reference
env1.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ham/hamsterdb.h>
Data Structures
struct customer_t
struct order_t
Macros
#define MAX_DBS 2
#define DBNAME_CUSTOMER 1
#define DBNAME_ORDER 2
#define MAX_CUSTOMERS 4
#define MAX_ORDERS 8
Functions
void error (const char *foo, ham_status_t st)
int main (int argc, char **argv)
Macro Definition Documentation
#define DBNAME_CUSTOMER 1
Definition at line 35 of file env1.c.
Referenced by main().
#define DBNAME_ORDER 2
Definition at line 36 of file env1.c.
Referenced by main().
#define MAX_CUSTOMERS 4
Definition at line 38 of file env1.c.
Referenced by main().
#define MAX_DBS 2
Definition at line 33 of file env1.c.
Referenced by main().
#define MAX_ORDERS 8
Definition at line 39 of file env1.c.
Referenced by main().
Function Documentation
void error (const char * foo, ham_status_t st)
A simple example, which creates a database environment with several databases.
Definition at line 28 of file env1.c.
References ham_strerror().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 57 of file env1.c.
References order_t::assignee, order_t::customer_id, ham_record_t::data, ham_key_t::data, DBNAME_CUSTOMER, DBNAME_ORDER, error(), HAM_AUTO_CLEANUP, ham_cursor_close(), ham_cursor_create(), HAM_CURSOR_FIRST, ham_cursor_move(), HAM_CURSOR_NEXT, ham_db_insert(), ham_env_close(), ham_env_create(), ham_env_create_db(), ham_env_open(), ham_env_open_db(), HAM_KEY_NOT_FOUND, HAM_PARAM_KEY_TYPE, HAM_SUCCESS, HAM_TYPE_UINT32, customer_t::id, order_t::id, MAX_CUSTOMERS, MAX_DBS, MAX_ORDERS, customer_t::name, ham_record_t::size, and ham_key_t::size.