hamsterdb Embedded Database: samples/env2.c File Reference
env2.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ham/hamsterdb.h>
Data Structures
struct customer_t
struct order_t
Macros
#define MAX_DBS 3
#define DBNAME_CUSTOMER 1
#define DBNAME_ORDER 2
#define DBNAME_C2O 3 /* C2O: Customer To Order */
#define DBIDX_CUSTOMER 0
#define DBIDX_ORDER 1
#define DBIDX_C2O 2
#define MAX_CUSTOMERS 4
#define MAX_ORDERS 8
Functions
void error (const char *foo, ham_status_t st)
int main (int argc, char **argv)
Macro Definition Documentation
#define DBIDX_C2O 2
Definition at line 42 of file env2.c.
Referenced by main().
#define DBIDX_CUSTOMER 0
Definition at line 40 of file env2.c.
Referenced by main().
#define DBIDX_ORDER 1
Definition at line 41 of file env2.c.
Referenced by main().
#define DBNAME_C2O 3 /* C2O: Customer To Order */
Definition at line 38 of file env2.c.
Referenced by main().
#define DBNAME_CUSTOMER 1
Definition at line 36 of file env2.c.
Referenced by main().
#define DBNAME_ORDER 2
Definition at line 37 of file env2.c.
Referenced by main().
#define MAX_CUSTOMERS 4
Definition at line 44 of file env2.c.
Referenced by main().
#define MAX_DBS 3
Definition at line 34 of file env2.c.
Referenced by main().
#define MAX_ORDERS 8
Definition at line 45 of file env2.c.
Referenced by main().
Function Documentation
void error (const char * foo, ham_status_t st)
Similar to env1, an Environment with a customer- and an order-Database is created; a third Database is created which manages the 1:n relationship between the other two.
Definition at line 29 of file env2.c.
References ham_strerror().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 63 of file env2.c.
References order_t::assignee, order_t::customer_id, ham_record_t::data, ham_key_t::data, DBIDX_C2O, DBIDX_CUSTOMER, DBIDX_ORDER, DBNAME_C2O, DBNAME_CUSTOMER, DBNAME_ORDER, error(), HAM_AUTO_CLEANUP, ham_cursor_create(), ham_cursor_find(), ham_cursor_move(), HAM_CURSOR_NEXT, ham_db_find(), ham_db_insert(), HAM_DUPLICATE, HAM_ENABLE_DUPLICATE_KEYS, ham_env_close(), ham_env_create(), ham_env_create_db(), HAM_KEY_NOT_FOUND, HAM_ONLY_DUPLICATES, HAM_PARAM_KEY_TYPE, HAM_PARAM_RECORD_SIZE, HAM_SUCCESS, HAM_TYPE_UINT32, customer_t::id, order_t::id, MAX_CUSTOMERS, MAX_DBS, MAX_ORDERS, customer_t::name, ham_record_t::size, and ham_key_t::size.