hamsterdb Embedded Database: samples/server1.c File Reference
server1.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ham/hamsterdb.h>
#include <ham/hamsterdb_srv.h>
Macros
#define EXT ""
Functions
int main ()
Macro Definition Documentation
#define EXT ""
A simple example which creates a server with one Environment and several Databases. See client1.c for the corresponding client.
Definition at line 31 of file server1.c.
Referenced by main().
Function Documentation
int main ()
Definition at line 35 of file server1.c.
References EXT, HAM_AUTO_CLEANUP, ham_db_close(), HAM_ENABLE_DUPLICATE_KEYS, HAM_ENABLE_TRANSACTIONS, ham_env_close(), ham_env_create(), ham_env_create_db(), HAM_RECORD_NUMBER64, ham_srv_add_env(), ham_srv_close(), ham_srv_init(), and ham_srv_config_t::port.